### ISSUE TITLE
Just a Question 

### ISSUE THREAD

**Issue by SuperMarioo** [grayzu/DSCPullServerUI#1]
HI Mark , 

Great work !! 

I have set this up on my lab env , but for some reasons nodes are not fully reporting to Pull Server . 

I cant see for example what DSC resources were used  .

StatusData column  not containing every information as I would get from Get-DSCConfigurationStatus cmdlet.

Regards 

Mariusz

**Comment by SuperMarioo** [comment]
Ignore my question its all working .

**Comment by grayzu** [comment]
Sounds good! Sorry for the delayed response. Missed this but let me know if you have any other questions or issues.
