### ISSUE TITLE
Parsing JSON StatusData

### ISSUE THREAD

**Issue by corydwood** [grayzu/DSCPullServerUI#2]
Hi Mark,

Do you know if there's an easy way to update this to parse the StatusData field that currently contains the raw JSON data into separate fields so we can see things like what resources are/aren't in the desired state.

A better question would be if you know if Microsoft has any plans on making the awesome DSC reporting that's available in Azure available for on-premise. $6/server/month is pretty expensive if all you're using it for is reporting DSC status for on-premise servers.

**Comment by grayzu** [comment]
Cory, 

I would not say that there is an "easy" way to parse the JSON to get the information that you are looking for but it certainly can be done. The JSON is structured so you can use PowerShell or .Net to get what you need / want from it. I wanted to do some basic parsing for this UI but did not have time to get it done. If you provide some examples of things you need in reporting and create a new enhancement issue for it, I will try to update this project to include some examples for how to do this.

Unfortunately I cannot speak to whether or not MSFT has plans to invest more in the on-prem pull server. I can say that we do listen to customer feedback about needs / wants like this so please provide feedback on [uservoice](https://windowsserver.uservoice.com/forums/301869-powershell). I know there are already some suggestions for this so vote them up if it is important to you. 

Also feel free to provide feedback to the Azure Automation DSC (AA DSC) team on their pricing. If the price is the only thing that is preventing you from using AA DSC, I know they would want to hear that from customers like you. 

MarkG
